=== JeffreyB04/Sistema-grupos-de-trabajo/HTMLutils_2.1.3/src/main/java/cr/ac/una/html/version_info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="version_info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="version"/>
                <xs:element ref="subversion"/>
                <xs:element ref="revision"/>
                <xs:element ref="created"/>
                <xs:element ref="history"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="version" type="xs:integer"/>
    <xs:element name="subversion" type="xs:integer"/>
    <xs:element name="revision" type="xs:integer"/>
    <xs:element name="created" type="xs:date"/>
    <xs:element name="history">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="entry"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="entry">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="date"/>
                <xs:element ref="author"/>
                <xs:element ref="comments" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="date" type="xs:date"/>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="comments" type="xs:string"> </xs:element>
</xs:schema>

=== JeffreyB04/Sistema-grupos-de-trabajo/HTMLutils_2.1.3/src/main/java/cr/ac/una/html/version_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<version_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="version_info.xsd">
    <version>2</version>
    <subversion>1</subversion>
    <revision>3</revision>
    <created>2022-07-16</created>
    <history>
        <entry>
            <date>2022-07-16</date>
            <author>Georges Alfaro S.</author>
            <comments>version 2.0.1</comments>
        </entry>
        <entry>
            <date>2023-04-05</date>
            <author>Georges Alfaro S.</author>
            <comments>version 2.1.0</comments>
        </entry>
        <entry>
            <date>2023-08-27</date>
            <author>Georges Alfaro S.</author>
            <comments>version 2.1.3</comments>
        </entry>
    </history>
</version_info>
